@echo off
cls

title [ GHOST ] 😈💻 Global-Protect Host Offline Support Tool 

echo ================================================================
echo [ GHOST ] Global-Protect Host Offline Support Tool 
echo ================================================================
echo [1] Deteniendo servicio PanGPS...

timeout /t 3 /nobreak >nul
cls

echo ================================================================
echo [ GHOST ] Global-Protect Host Offline Support Tool 
echo ================================================================
echo [1] Deteniendo servicio PanGPS...
echo [2] Reiniciando servicio de GlobalProtect...

timeout /t 3 /nobreak >nul
cls

echo ================================================================
echo [ GHOST ] Global-Protect Host Offline Support Tool 
echo ================================================================
echo [1] Deteniendo servicio PanGPS...
echo [2] Reiniciando servicio de GlobalProtect...
echo [3] Limpiando caché de DNS...
ipconfig /flushdns
timeout /t 3 /nobreak >nul
cls

echo ================================================================
echo [ GHOST ] Global-Protect Host Offline Support Tool 
echo ================================================================
echo [1] Deteniendo servicio PanGPS...
echo [2] Reiniciando servicio de GlobalProtect...
echo [3] Limpiando caché de DNS...
echo [4] Liberando IP del dispositivo...
ipconfig /release
timeout /t 3 /nobreak >nul
cls

echo ================================================================
echo [ GHOST ] Global-Protect Host Offline Support Tool 
echo ================================================================
echo [1] Deteniendo servicio PanGPS...
echo [2] Reiniciando servicio de GlobalProtect...
echo [3] Limpiando caché de DNS...
echo [4] Liberando IP del dispositivo...
echo [5] Solicitando una IP nueva...
ipconfig /renew
timeout /t 3 /nobreak >nul
cls

echo ================================================================
echo [ GHOST ] Global-Protect Host Offline Support Tool 
echo ================================================================
echo [1] Deteniendo servicio PanGPS...
echo [2] Reiniciando servicio de GlobalProtect...
echo [3] Limpiando caché de DNS...
echo [4] Liberando IP del dispositivo...
echo [5] Solicitando una IP nueva...
netsh winsock reset
netsh int ip reset
timeout /t 3 /nobreak >nul
cls

echo ================================================================
echo [ GHOST ] Global-Protect Host Offline Support Tool 
echo ================================================================
echo [1] Deteniendo servicio PanGPS...
echo [2] Reiniciando servicio de GlobalProtect...
echo [3] Limpiando caché de DNS...
echo [4] Renovando configuración de red con IpConfig...
echo [5] Renovando configuración de red con NetSH...
echo [6] Terminando procesos de GlobalProtect...
taskkill /F /IM PanGPA.exe /T >nul
taskkill /F /IM PanGPS.exe /T >nul
timeout /t 3 /nobreak >nul
cls

echo ================================================================
echo [ GHOST ] Global-Protect Host Offline Support Tool 
echo ================================================================
echo [1] Deteniendo servicio PanGPS...
echo [2] Reiniciando servicio de GlobalProtect...
echo [3] Limpiando caché de DNS...
echo [4] Renovando configuración de red con IpConfig...
echo [5] Renovando configuración de red con NetSH...
echo [6] Terminando procesos de GlobalProtect...
echo [7] Reiniciando GlobalProtect...
start "" "C:\Program Files\Palo Alto Networks\GlobalProtect\PanGPA.exe" >nul
timeout /t 3 /nobreak >nul


cls
echo =======================================
echo Proceso finalizado con exito.
echo Reintenta la conexion a GlobalProtect.
echo =======================================
echo.
pause
exit
